### ISSUE TITLE
in lastest version position sensor isn't available

### ISSUE THREAD

**Issue by pilot1981** [arjenvrh/audi_connect_ha#100]
in lastest version position sensor isn't available, there is a way to fix it?

it isn't possibile to obtain this information using API/APP AUDI CONNECT?

**Comment by FilippoS1973** [comment]
Same here

**Comment by pilot1981** [comment]
I see position in audi connect app, so I suppose it’s again possibile to obtain position in HA…?!

**Comment by pilot1981** [comment]
Now it seems to work again
