### ISSUE TITLE
Add support for HACS

### ISSUE THREAD

**Issue by rafuz** [arjenvrh/audi_connect_ha#11]
It would be nice if this component could be updated from [HACS ](https://github.com/custom-components/hacs)

**Comment by olle-j** [comment]
I tried to add this repo to HACS and it downloaded the component. The repository structure seems ok. But I havent tried to start the component yet..

But I think there is some stuff that can be improved. Like a description and topics for the repository. It mostly nice to have things that can be setup independently from HACS.

https://hacs.xyz/docs/publish/start#general-requirements

**Comment by olle-j** [comment]
I made i quick fork to try this out. I added a description, added some topics and created a release. This looks very nice in HACS! :)

I'm not sure that every MUST is fulfilled. But this looks like an easy win. 

![image](https://user-images.githubusercontent.com/58069282/69415497-081fd680-0d15-11ea-9275-420d0eaf8393.png)

![image](https://user-images.githubusercontent.com/58069282/69415548-1cfc6a00-0d15-11ea-8b6a-07e9d300e268.png)

**Comment by olle-j** [comment]
I also added a info.md, to be shown in the HACS interface.

![image](https://user-images.githubusercontent.com/58069282/69418185-74e99f80-0d1a-11ea-8b0d-2e38036d4063.png)

**Comment by rafuz** [comment]
Seems great, when will it be available in hacs repo list?

**Comment by olle-j** [comment]
I'm no maintainer of this repo, I'm afraid.. 

But you should be able to add it yourself to your own HACS configuration as of now if you want. Just add "https://github.com/arjenvrh/audi_connect_ha". Thats what I did as a prove of concept.
