### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by FilippoS1973** [arjenvrh/audi_connect_ha#111]
I have this errors:
- User input malformed: expected str for dictionary value @ data['region']
- Invalid credentials

my problem or Audi api problem or ?

**Comment by kazuraghi** [comment]
Same issue for me.
Credentials are correct (the myaudi site is working with this credentials).
Anyway, I can't get car info nor from audi site, nor from MyAudi app (I can only lock/unlock).
I think there are some issues on Audi API.....

**Comment by t0bias-r** [comment]
See my latest pr #110 - it should fix it

**Comment by kazuraghi** [comment]
Thanks @t0bias-r ! Working!

**Comment by FilippoS1973** [comment]
Perfect! It works also here.Thank you   Da: kazuraghiInviato: lunedì 31 gennaio 2022 10:03A: arjenvrh/audi_connect_haCc: FilippoS1973; AuthorOggetto: Re: [arjenvrh/audi_connect_ha] Login error (Issue #111) Thanks @t0bias-r ! Working!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by FilippoS1973** [comment]
Thank you, it works!
