### ISSUE TITLE
CHange from Km to Miles?

### ISSUE THREAD

**Issue by monsieurlatte** [arjenvrh/audi_connect_ha#12]
Just got this setup and dialed in (way awesome by the way), is there anyway to change it to deliver Miles and such instead of metric units?

**Comment by sutty74** [comment]
Quick conversion should do the trick.
 
 - platform: template
    sensors:
      audi_a5_fuel_range_mi:
        friendly_name: Fuel Range
        unit_of_measurement: mi
        value_template: >
          {{ (states ('sensor.audi_a5_sportback_range') | float/1.609) | round (0)}}

**Comment by arjenvrh** [comment]
Added support for imperial units using home assistant's configuration (add unit_system: imperial to the homeassistant section in configuration.yaml)

**Comment by monsieurlatte** [comment]
Dude you rock!  Thanks so much for doing this, it's like a delayed christmas present, one thing I ask, you have miles spelled as "mil", is it possible to change it to "mi" like most others have it?  No rush and if not possible all good!

**Comment by arjenvrh** [comment]
Well apparently I'm so into the metric system that I don't know how to properly abbreviate miles. :-)
Fixed

**Comment by jarrah31** [comment]
Would it be possible to add a separate option within audi_connect_ha to override Home Assistant's unit_system for this integration please?
I prefer to see my car stats in miles, but if I change the unit_system to imperial in configuration.yaml, it messes up other HA stats such as my weather information, changing temperature from Celsius to Fahrenheit, so I need to leave unit_system set to metric.
TIA

**Comment by Rustymage** [comment]
add this to your config:

change the bit in bold!

```
sensor mileage:
  platform: template
  sensors:
    km_to_mi_convert:
      unit_of_measurement: 'miles'
      value_template: "{{ (states('**sensor.audi_a4_avant_mileage**') | float / 1.6) | round(0)}}"
```
