### ISSUE TITLE
Just updated - only two entities

### ISSUE THREAD

**Issue by jaygrovr** [arjenvrh/audi_connect_ha#120]
Thanks for updating this integration.  I am not sure I follow what was done, but I had to delete this integration and re-install it since it wasnt connecting.  The prior setup I think discovered 11 entities, and now, its only discovering 2.  Any idea why its not getting all the great information that I am looking for?

Thanks again for the great work.

jason

**Comment by andrewoke** [comment]
Seeing the same thing. Migrated to new VM and now only have the 2 entities. Using latest version in HACS.

**Comment by mackay2k4** [comment]
I had the same problem. Solution is to log on to https://www.audi.de/myaudi/ and finish the car setup config there. I had to enter the Vehicle Code (you get this with the purchase of your car on the key it’s a 10 digits scratch off code) and then reset the main user of the vehicle.
Once done I got all the sensors and stuff back again.

**Comment by andrewoke** [comment]
Hmmm, I think it has to do more with regional api's. I'm now only to set it up with ca as the region (in canada) and it appears that to get that data it calls 

`
userinfo.my.audi.com/bvh/v1`
