### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by korsmann** [arjenvrh/audi_connect_ha#123]
Did they change log in, again...? unable to connect.

**Comment by chemgeek** [comment]
Same issue

**Comment by mpredfearn** [comment]
Looks like it, same here :-(

**Comment by derhappy** [comment]
Same here (Germany) since yesterday. The app is working.

**Comment by jtonk** [comment]
Same here, wondering why the iOS app still works, because the iOS app isn't updated.

**Comment by t0bias-r** [comment]
The login with Android myAudi version 4.5.x is obsolet and deactivated on the Audi servers.

The X_QMAuth SHA calculation (`xqmauth_secret`) is changed in version 4.6.0.
I'm already testing the new secret and will make a PR later today or tomorrow.

**Comment by mgmtotorsperformance** [comment]
same in Poland, not working since yesterday

**Comment by chemgeek** [comment]
Every time this happens, the system in my Audi throws an error and erases all my shortcut in the MMI.  Crazy what trash Audi is.  Thanks for your work on this integration.

**Comment by devganny** [comment]
Same here:
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:89
Integration: Audi Connect
First occurred: 23:17:36 (1 occurrences)
Last logged: 23:17:36
Login to Audi service failed: 'access_token'

I do not understand, why audi is not able to offer an available service. Other brands within the vw-group do not have these issues. I like the hardware and the design of the cars, but the digital integration is a nightmare.

**Comment by danielsmith89** [comment]
As much as it's frustrating, remember nothing about this integration is official and it's using the Audi web services in a way that isn't officially supported. There is no point in blaming/trashing Audi. Hopefully there will be a resolution to this soon.

**Comment by chemgeek** [comment]
> As much as it's frustrating, remember nothing about this integration is official and it's using the Audi web services in a way that isn't officially supported. There is no point in blaming/trashing Audi. Hopefully there will be a resolution to this soon.

No, the Audi Connect and MMI system is terrible.  I have a 2021 Etron and the entire system is a nightmare.  The Hardware on the car is really nice, but the tech is terrible.  I applaud the coder of this integration that he/she is able to somehow get it to work given the crap Audi pushes out.

**Comment by devganny** [comment]
My comment was not focused on the interoperability with this homeassistant integration. It is focused on the general availability, to web integration, the features, the stability and the support of audi. This is all years behind Tesla and other competitors. I am german and I drive Audi since more den 25 years now, but I fear, that the german car manufacturers will lose their ground when they will not speed up in their digital development. Espeacially Audi has so many problems with their bad software solutions.

**Comment by t0bias-r** [comment]
see #124

**Comment by Gunth** [comment]
Confirm, back again on my side with the PR

**Comment by damienheiser** [comment]
> see PR #124

Thank you for this PR and update, can confirm it works, appreciations for your hard work and contributions!

**Comment by tornenen** [comment]
same problem here

**Comment by Paulus88** [comment]
> download the zip file from here (select the green code button -> Download ZIP): https://github.com/t0bias-r/audi_connect_ha/tree/login_app-v4_6
> 
> unzip and overwrite the files in the home assistant folder `\config\custom_components\audiconnect` note: you might have some issues with file permissions, but that depends on your installation.
> 
> reload HA

This works perfect :)

**Comment by jaygrovr** [comment]
I am still getting "invalid credentials".  with the latest build.  I have wiped the folder in custom integrations and tried redownloading the files.  Still no luck getting HA to sign into audi.  I have checked my credentials just signing into normal audi website.

**Comment by Paulus88** [comment]
> I am still getting "invalid credentials". with the latest build. I have wiped the folder in custom integrations and tried redownloading the files. Still no luck getting HA to sign into audi. I have checked my credentials just signing into normal audi website.

To make life easy I just forked [t0bias-r](https://github.com/t0bias-r/audi_connect_ha/tree/login_app-v4_6) repository:
https://github.com/Paulus88/audi_connect_ha

Added this to HACS. I do notice other errors in the logs so its probably not finished yet (hence no new release) but this version is working for me :)

**Comment by jaygrovr** [comment]
so what is the best way to test this out?  I tried re-downloading on the hacs repository.. and restarted, but its still saying incorrect credentials.
Jason
    On Tuesday, February 22, 2022, 11:11:38 AM PST, Paulus88 ***@***.***> wrote:  
 
 



I am still getting "invalid credentials". with the latest build. I have wiped the folder in custom integrations and tried redownloading the files. Still no luck getting HA to sign into audi. I have checked my credentials just signing into normal audi website.


To make life easy I just forked t0bias-r repository:
https://github.com/Paulus88/audi_connect_ha

Added this to HACS. I do notice other errors in the logs so its probably not finished yet (hence no new release) but this version is working for me :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Paulus88** [comment]
> so what is the best way to test this out?>

1. Go to HACS and remove the current Audi connect repository.
2. While in HACS go to the 3 dots usually in the top/right corner.
3. Select Custom repositories.
4. Add https://github.com/Paulus88/audi_connect_ha and choose Integration.
5. Click Add and restart home assistant once restarted add your Audi Connect device again.

![image](https://user-images.githubusercontent.com/25663775/155228231-963e8249-df70-47c1-be06-25c13971fc55.png)

For now this is for me my workaround until [arjenvrh](https://github.com/arjenvrh) releases the update here :)

**Comment by jaygrovr** [comment]
This is amazing.. I will figure out a way to contribute!
Jason
    On Tuesday, February 22, 2022, 02:13:43 PM PST, Paulus88 ***@***.***> wrote:  
 
 



so what is the best way to test this out?>

   
   - Go to HACS and remove the current Audi connect repository.
   - While in HACS go to the 3 dots usually in the top/right corner.
   - Select Custom repositories.
   - Add https://github.com/Paulus88/audi_connect_ha and choose Integration.
   - Click Add and restart home assistant once restarted add your Audi Connect device again.



For now this is for me my workaround until arjenvrh releases the update here :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
