### ISSUE TITLE
How to create a button to lock/unlock doors in lovelace?

### ISSUE THREAD

**Issue by LCMilstein** [arjenvrh/audi_connect_ha#127]
The documentation indicates that there is a service "audiconnect.execute_vehicle_action" which should take "lock" as a value and somehow I have to include the vin as a parameter, but I can't figure out how this works.

I've tried to create a button card with a tap action of call service and use the audiconnect.execute_vehicle_action as the service, but that throws errors, and I don't see where to put the VIN...

I've also created a button for "lock.none_door_lock" but that only shows the state, it doesn't effect the state.
AND, I've created an entity card for this "lock.none_door_lock" where when I tap the card and pull up the more detailed view there are actions for both LOCK and UNLOCK showing, but tapping those does nothing...

Can someone point me to something they have working?

Thank you!

**Comment by duckend** [comment]
service: audiconnect.execute_vehicle_action
data:
  vin: WBANXXXXXX1234567
  action: lock

Services tab under Developer Tools screen of Home Assistant gives examples like the above.

**Comment by LCMilstein** [comment]
Thank you, @duckend, but I'm still missing something... I went to developer tools, selected "Audi Connect: execute_vehicle_action" as the service and saw the example data. I replaced the vin with the vin to my car and then clicked the "Call Service" button... nothing happened. I waited to see if it just takes time to go through Audi Connect (since it takes time if I try to lock the car from the MyAudi app), but still NOTHING. I also tried to put the vin and action lines in the service data field of a button with a tap action of "call service" and selected the right service, but still... no actual response from the vehicle.

**Comment by duckend** [comment]
```
  - service: audiconnect.execute_vehicle_action
    data:
      vin: wauzxxxxxxxxxxxx
      action: stop_charger
```

I’ve no experience of attempting to lock/unlock the car but the above is working as expected in an automation, as do start charger and start/stop climate.

I do see the documents state 

`“Note that certain action require the S-PIN to be defined in the configuration.”`

Do you have that configured? We don’t need it to control charging but I would expect locking would be at a higher security level?

**Comment by LCMilstein** [comment]
In the dialog that appears when installing the Audi Connect configuration (second step after copying the files for the HACS/Custom Configuration setup), there are 5 fields:

1. Username
2. Password
3. S-Pin
4. Region
5. Interval

I have all 5 completed, including the S-Pin. Am I supposed to put it somewhere in the yaml as well?

**Comment by bavala3010** [comment]
I created a button card with the following code:
```
type: button
tap_action:
  action: toggle
show_state: true
entity: lock.audi_e_tron_sportback_55_door_lock
icon_height: 30px
name: lock/unlock car doors
```

-> on the entity line, replace **audi_e_tron_sportback_55_door_lock** with your entity and make sure you have **lock.** before the entity name.

The icon shows the state (locked/unlocked) and when unlocked it's in yellow.

I also did some automations. Every night at 9 PM, check if the doors are locked. If not, it automatically sends the lock command to the car and sends a message to my phone saying something like "The car doors were still open, luckily I closed them for you."

**Comment by bavala3010** [comment]
For some actions, the PIN code is required. So make sure that the PIN code was correctly entered when you installed the integration in Home Assistant.

**Comment by LCMilstein** [comment]
I have done so... this is the 10-Letter code on the scratched-off portion of the plastic tag that came attached to the keys, right?

**Comment by bavala3010** [comment]
No, that's not the code. I have a 5 digit code. You can reset your code on the Audi website: https://my.audi.com/account/account-settings

**Comment by LCMilstein** [comment]
Oh!!! Ok, can you provide a bit more direction on where within the site? 
When I click the link, the site identifies me as being in the US; I click "Go to myAudi" and it redirects to https://www.audiusa.com/myaudi. From there, there are a LOT of things I could do, including clicking "Let's go" as the main AI for the "Unlock your digital ownership experience," but no matter where I look within myAudi, I don't see a pin or the ability to reset anything at all. 

In the FAQs, there's this:

>  [Where do I find my myAudi PIN and what is it for?]
> (https://www.audiusa.com/help#content_accordion_21310134661-4)
> Your myAudi PIN is used to link your vehicle with your myAudi account. The PIN is found inside your online myAudi account or MMI Connect app. With successful entry of the myAudi PIN you will be able to use features like sending destinations to the vehicle and personalize certain myAudi services (if applicable).

But the only pin I can find in the app is a 4-digit pin, not a 5-digit one... That's under Profile->Account Settings->PIN
Is that what I should use?

**Comment by LCMilstein** [comment]
This seems to have worked! It's still calling the entity "none" per my other thread, which I'll pick up there, and throwing a lot of errors to the log around certain sensors, but it's actionable! Thank you.

**Comment by LCMilstein** [comment]
AND... it does "work" in that it locks the car if I press the button, but if the car is locked and I press the button to unlock (toggle from lock to unlock), it unlocks briefly and then re-locks about a minute later. Is this because I've set the polling interval too short? A check every 10 minutes isn't super helpful as I don't want data that's 10 minutes old... Thoughts?

**Comment by insert10p** [comment]
When it locks itself that's probably the car. If I unlock mine with the key fob, Audi app or Home Assistant but don't open a door then the car locks itself automatically
