### ISSUE TITLE
Initialize problem

### ISSUE THREAD

**Issue by antoinevandenhurk** [arjenvrh/audi_connect_ha#13]
Initialize problem since update to HA 103.0
`2019-12-13 19:22:01 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] 502, message='Bad Gateway', url='https://msg.audi.de/fs-car/core/auth/v1/Audi/DE/token
2019-12-13 19:22:11 ERROR (MainThread) [homeassistant.setup] Setup failed for audiconnect: Integration failed to initialize.`

**Comment by rafuz** [comment]
Same error here, something changed on Audi backend.

**Comment by typendetinus** [comment]
Here as well, Audi's app still works though.

**Comment by arjenvrh** [comment]
Problem was caused due to api change. The old api is back online, latest update changes the integration to new api
