### ISSUE TITLE
2021 Q5e Not Displaying Climatisation/Charging/Preheater/Window Heating Controls

### ISSUE THREAD

**Issue by coreywillwhat** [arjenvrh/audi_connect_ha#138]
While available in the myAudi app, the following devices are not available for sending commands when using this integration with 2021 Audi Q5e:
        'start_climatisation', 'stop_climatisation, 'start_charger', 'start_timed_charger', 'stop_charger',
        'start_preheater', 'stop_preheater, 'start_window_heating', 'stop_window_heating'

Lock/Unlock commands are available and work as expected.
All Sensor/Binary Entities appear to be available including climatisation and charging.

**Comment by coreywillwhat** [comment]
misunderstanding of services vs devices

**Comment by coreywillwhat** [comment]
I realized you had to use service calls for these commands. There is no "front end" display or controls for these. That said, I haven't put the time in, or raised a question, to figure out how to set the climate temp or seat heaters.

**Comment by kuno1224** [comment]
Ah ok. Thank you for responding quickly!

**Comment by kuno1224** [comment]
It worked flawlessly, really not difficult

**Comment by coreywillwhat** [comment]
Awesome, glad you got it! Any chance you figured out how to set climate temp or seat warmers?

**Comment by kuno1224** [comment]
Good point. Frankly, I just started a climatisation. The settings I usually keep the same even when I use the Audi app. (it is a A6 TFSIe).
So frankly, have not tried to set/change the temp. Would be interesting anyway. If I find out, I will let you know
