### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by lighty78** [arjenvrh/audi_connect_ha#144]
Getting Invalid credentials after updating the HASS. I know the credetials are correct, as they are working to login to the app and to the website.

**Comment by peter-myklebust** [comment]
I have the same issue, "Invalid credentials". Login works elsewhere

**Comment by lighty78** [comment]
Yes!  That did the thing!  Thanx for noticing!

**Comment by lighty78** [comment]
There is an PR. https://github.com/arjenvrh/audi_connect_ha/pull/143
