### ISSUE TITLE
Login to Audi service failed: 'access_token'

### ISSUE THREAD

**Issue by HaxxHaris** [arjenvrh/audi_connect_ha#146]
Hello,

Does anyone else have the same problem?

The integration stopped working since 16-06-2022

I have not changed the password to my account, I can still log in via the web http://myaudi.com/ and the app on iPhone

Have also tried uninstalling the integration and logging in again, but then it is not possible to log in at all. It says that credentials are not valid or something like that does not remember exactly.

Before I uninstall, I see these error messages in the log:

Login to Audi service failed: 'access_token'
17:18:57 – (ERROR) Audi Connect (custom integration) - message first occurred at 16:47:45 and shows up 4 times
Login to Audi service failed, trying again in 10 seconds
17:18:46 – (ERROR) Audi Connect (custom integration) - message first occurred at 16:47:23 and shows up 8 times

Everything at HA is up to date to the latest version.
I run my HA as a virtual machine, so I took a snapshot a month ago that I backed up and checked if it works, but the same problem, thought if it could be an update va HA core or something else.

Also via http://myaudi.com/ changed to the same password again and tested but it does not work ..

I live in Sweden, have tested DE as a country and even without.

Does anyone have any suggestions on what I can check / do?

**Comment by HaxxHaris** [comment]
> 

Thank you so much for your work :) It works really well again after your fix :)

**Comment by simonince** [comment]
Ah not my hard work, I was just lucky to find the PR by @t0bias-r, but pleased it's working again for you! I did notice the data Audi exposes has changed which is interesting. But I love using this plugin.
