### ISSUE TITLE
Password change or PIN change

### ISSUE THREAD

**Issue by martennienhuis** [arjenvrh/audi_connect_ha#15]
Great feature!! Good work.
How can I change my password or PIN. The only way I found so far is te remove the integration, restart homeassistant and then reinstall integration. Is it possible to configure the username and password somewere so you can change it in an easy way? Or is it possible to start the dialog to enter the username and password and etc.

**Comment by heymoe** [comment]
It might not be the safest thing to do but you can manually edit the "core.config_entries" file located in the ".storage" folder under your config directory. Search for the Audi Connect integration settings, change what you need and then restart Home Assistant. I just had to do this to add my SPIN and it worked for me but your mileage may vary.

I would recommend making a backup just in case something goes sideways.

**Comment by arjenvrh** [comment]
I haven't figured out how to enable changing settings in the config flows of HA. Although options can be added, I don't think these are intended for passwords and PIN codes. So for now I'm afraid the only option is to remove the integration and add it again (or manually edit the core.config_entries file as heymoe stated)
