### ISSUE TITLE
audiconnect.execute_vehicle_action

### ISSUE THREAD

**Issue by aocaoc** [arjenvrh/audi_connect_ha#16]
Hey Arjen,

Sending along a VIN number when sending data isn't working for me.
So far I have this, which should be valid.

{ "action": "call_service", "service": "audiconnect.execute_vehicle_action", "action": "unlock" }

How can i send along the VIN number?

Kind regards,
Track

**Comment by aocaoc** [comment]
I solved it, I can now open and close my car with voice command (Google assistant).
Amazing work on the plugin!

**Comment by arjenvrh** [comment]
I don't think I'll be adding vw/skoda, but who knows? A Volkswagen integration already exists and it's difficult to test all brands without actually owning such a car. Perhaps the api's will become more similar to the volkswagen me platform, or some skoda owner can add to the project.
