### ISSUE TITLE
Failed to Initialize: 404 Not Found

### ISSUE THREAD

**Issue by agentadam-code** [arjenvrh/audi_connect_ha#168]
Until a day or two ago everything was working. Rebooted server today and am getting:

`2023-02-27 12:43:11.800 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 404, message='Not Found', url=URL('https://idkproxy-service.apps.na.vwapps.io/v1/na/openid-configuration')`

Looking at previous issues I see the same errors. Maybe this is an API update?

**Comment by jhejmann** [comment]
Just tried to run initialize for the first time and getting "Invalid credentials" error. Double checked and tried 2 accounts.

**Comment by agentadam-code** [comment]
@jhejmann, me too. After reporting I tried to initialize and getting that same error. When I look at the logs though the 'invalid credentials error' coincides with the 404. I am convinced they changed their API setup again.

**Comment by JamieP83** [comment]
Same issue here

**Comment by andig** [comment]
Confirmed. It is no longer possible, to exchange the IDK token.

**Comment by simonepittis** [comment]
problem in the GW URL. not in the code. All the domain it's down (EMEA):
https://start.vwapps.io/ => 404 Not Found: Requested route ('start.vwapps.io') does not exist.

**Comment by JimRnewell** [comment]
same here broken after a reboot today

**Comment by andig** [comment]
See https://github.com/evcc-io/evcc/commit/5bdc578187b9cfe5a197cddff242906a03515db9

**Comment by Kolbi** [comment]
Just a question is this git still maintained or move over to https://github.com/Cyr-ius/hass-audiconnect @Cyr-ius ?

**Comment by simonepittis** [comment]
> Just a question is this git still maintained or move over to https://github.com/Cyr-ius/hass-audiconnect @Cyr-ius ?

This forked works! no issues :-)

**Comment by gllmlbrt** [comment]
https://github.com/arjenvrh/audi_connect_ha/issues/169#issuecomment-1450622794
