### ISSUE TITLE
Problem to solve DNS name idkproxy-service.apps.emea.vwapps.io

### ISSUE THREAD

**Issue by pilot1981** [arjenvrh/audi_connect_ha#173]
In log now I found this issue:

Login to Audi service failed: Cannot connect to host idkproxy-service.apps.emea.vwapps.io:443 ssl:default [Name does not resolve]

your HA is able to solve it?

which ip address do you lookup in Europe?

**Comment by HaxxHaris** [comment]
Same problem here, tried resolve with google DNS and same error...

Server:  dns.google
Address:  8.8.8.8

*** dns.google can't find idkproxy-service.apps.emea.vwapps.io: Non-existent domain

**Comment by pilot1981** [comment]
could be related to issue #162? https://github.com/arjenvrh/audi_connect_ha/issues/162#issue-1454098750

**Comment by pilot1981** [comment]
solved using workaroung in #169
