### ISSUE TITLE
Audi Connect Down Again

### ISSUE THREAD

**Issue by rosshenning** [arjenvrh/audi_connect_ha#174]
This appears to be the same issue all over again (after it was just fixed) where Audi has changed soemthing:

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:94
Integration: Audi Connect
First occurred: 12:06:12 PM (9 occurrences)
Last logged: 12:21:49 PM

Login to Audi service failed, trying again in 10 seconds
Login to Audi service failed: Cannot connect to host idkproxy-service.apps.na.vwapps.io:443 ssl:default [Name does not resolve]

_Originally posted by @rosshenning in https://github.com/arjenvrh/audi_connect_ha/issues/169#issuecomment-1462446846_

**Comment by Kolbi** [comment]
Should be fixed which this PR: https://github.com/arjenvrh/audi_connect_ha/pull/172 ?

**Comment by laitco** [comment]
No, same problem since yesterday. Tried to reinstall and applied the fix. Did not help..

**Comment by rosshenning** [comment]
> Should be fixed which this PR: #172 ?

It WAS fixed, but Audi did something again on 3/9/23 to break it.

**Comment by zenyagami** [comment]
I have the same issue :/ I'm running the latest version by HACS and I can't connect to my Audi, is there any workaround?

**Comment by brettonw** [comment]
This fork seems to have been rewritten and still works rn: https://github.com/Cyr-ius/hass-audiconnect. The HACS component with the arjenvrh original is not being updated, near as I can tell - so you have to do a manual clone in your custom components directory.

**Comment by rosshenning** [comment]
> This fork seems to have been rewritten and still works rn: https://github.com/Cyr-ius/hass-audiconnect. The HACS component with the arjenvrh original is not being updated, near as I can tell - so you have to do a manual clone in your custom components directory.

Hi Brettonw, I appreciate the feedback on using this fork.  I can't find any info on how to do a "manual Clone" in the custom components directory.  Can you point me to where I can find out more about doing this?  Thanks in advance.

**Comment by rosshenning** [comment]
> This fork seems to have been rewritten and still works rn: https://github.com/Cyr-ius/hass-audiconnect. The HACS component with the arjenvrh original is not being updated, near as I can tell - so you have to do a manual clone in your custom components directory.

Tried doing this just now....same result unfortunately.  It's not connecting.

**Comment by rosshenning** [comment]
Looking through everything, it appears that the latest issue is actually coming from audi_connect_account.py, and NOT from audi_services.py where the last issue was.  This is the error in my logs:

Logger: custom_components.audiconnect.audi_connect_account
**Source: custom_components/audiconnect/audi_connect_account.py:94**
Integration: Audi Connect
First occurred: 9:07:25 PM (18 occurrences)
Last logged: 9:29:37 PM

Login to Audi service failed, trying again in 10 seconds
Login to Audi service failed: Cannot connect to host idkproxy-service.apps.na.vwapps.io:443 ssl:default [Name does not resolve]

**Comment by Frankster-NL** [comment]
Is anyone else seeing some strange values in sensor.audi_e_tron_actual_charge_rate? I suspect this sensor would show the kWh rate of charging, but as I was connected to a 5kW charger it was showing values between 19,5 and 21,5...

**Comment by Giuliointhetube** [comment]
> This appears to be the same issue all over again (after it was just fixed) where Audi has changed soemthing:
> 
> Logger: custom_components.audiconnect.audi_connect_account Source: custom_components/audiconnect/audi_connect_account.py:94 Integration: Audi Connect First occurred: 12:06:12 PM (9 occurrences) Last logged: 12:21:49 PM
> 
> Login to Audi service failed, trying again in 10 seconds Login to Audi service failed: Cannot connect to host idkproxy-service.apps.na.vwapps.io:443 ssl:default [Name does not resolve]
> 
> _Originally posted by @rosshenning in [#169 (comment)](https://github.com/arjenvrh/audi_connect_ha/issues/169#issuecomment-1462446846)_

Same here. I tested all wor

**Comment by Giuliointhetube** [comment]
Same conne cation problem here

**Comment by gllmlbrt** [comment]
Hey there, your logs show that it still tries to resolve  idkproxy-service.apps.na.vwapps.io which suggests that your audi_connect_services.py was not updated as per PR #172 

the na.vwapps.io or emea.vwapps.io should not appear anymore in your codes...
It is now na.bff.cariad.digital for US and emea.bff.cariad.digital for the rest.

So your integration should try to resolve "na.bff.cariad.digital/login/v1/idk/openid-configuration"

**Comment by gllmlbrt** [comment]
> > Should be fixed which this PR: #172 ?
> 
> It WAS fixed, but Audi did something again on 3/9/23 to break it.

It still works great for me.
