### ISSUE TITLE
Relogin on fetching vehicle data

### ISSUE THREAD

**Issue by woopstar** [arjenvrh/audi_connect_ha#175]
I'm getting the below issue:

```
 File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 263, in get_vehicle_information
    response = VehiclesResponse()
Exception: Invalid json in get_vehicle_information
```

Added some debugging by printing the `rep_rsptxt` variable. The token is expired but never renewed.

```
2023-03-16 14:36:10.932 ERROR (MainThread) [custom_components.audiconnect.audi_services] {
  "requestid": "d0e1c89fe90899c9-a81220d507290775",
  "error":"401",
  "error_description":"User is not Authenticated using|Auth Server JWT|",
  "error_cause": [{
	"auth_method": "Auth Server JWT",
	"error_message": "The token is invalid. Exp time elapsed (1678973037), current time: 1678973770 ."
}]
}
```

This is the   exception I'm hitting:
https://github.com/arjenvrh/audi_connect_ha/blob/master/custom_components/audiconnect/audi_services.py#L261

It is using an outdated token.

If such an error happens, it must refresh the token again. So the `get_vehicle_information` function needs to be updated with some error handling.

**Comment by woopstar** [comment]
Switching the default login time to `0` seems to fix the issue tough, because it will cause it to refresh the token on HA restart / reload:

https://github.com/arjenvrh/audi_connect_ha/blob/master/custom_components/audiconnect/audi_connect_account.py#L49

**Comment by pilot1981** [comment]
> Switching the default login time to `0` seems to fix the issue tough, because it will cause it to refresh the token on HA restart / reload:
> 
> https://github.com/arjenvrh/audi_connect_ha/blob/master/custom_components/audiconnect/audi_connect_account.py#L49

what I have to modify? I don't understood...

**Comment by weaselbase1** [comment]
Doesn't seem to resolve this error.
