### ISSUE TITLE
Hass 2023.08 - unexpected keyword argument 'device_type' when calling entity_platform.py

### ISSUE THREAD

**Issue by gllmlbrt** [arjenvrh/audi_connect_ha#192]
Since HASS 2023.08 update, below issue pops up preventing the integration to run.

`Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:619
Integration: Device Tracker (documentation, issues)
First occurred: 2 August 2023 at 21:01:28 (3 occurrences)
Last logged: 08:03:15

Error adding entities for domain device_tracker with platform audiconnect
Error while setting up audiconnect platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'device_type'
`

**Comment by gllmlbrt** [comment]
Workaround found:

Delete line 80 `"device_type": self._component,` in audi_entity.py and restart HASS

**Comment by Flashlab2** [comment]
Thanks, this works!

**Comment by rgcouto** [comment]
Same here!

**Comment by Heelderpeel** [comment]
Thnx, works perfect for me

**Comment by euri911** [comment]
> Workaround found:
> 
> Delete line 80 `"device_type": self._component,` in audi_entity.py and restart HASS

Thanks for the info, now it works again.

However, what is the impact of this removal (if any)?

Cheers,
Evripidis

**Comment by Heelderpeel** [comment]
For the device tracker the same action works.
in device_tracker.py Simple put a # for  line 124 it looks like this:
_**#            "device_type": "device_tracker",**_

**Comment by TheDelta** [comment]
I think there is no impact, it seems to me that they added validation to the config and thats why it doesn't work anymore: (see history https://github.com/home-assistant/core/commits/42bca0f94a393ed841f03f7d60d99d2881851b47/homeassistant/helpers/device_registry.py)

If I look at https://developers.home-assistant.io/docs/device_registry_index/#device-properties then I don't see anything where device_type (or similar) would be needed.

**Comment by matteoopc** [comment]
Works! thanks!

**Comment by bigramonk** [comment]
> Workaround found:
> 
> Delete line 80 `"device_type": self._component,` in audi_entity.py and restart HASS

Thanks !!
Reloading the integration was enough for me, no need to restart HA

**Comment by wautersj** [comment]
> Workaround found:
> 
> Delete line 80 `"device_type": self._component,` in audi_entity.py and restart HASS

Works nicely! 
Thanks a bunch!
