### ISSUE TITLE
Is it still working ??

### ISSUE THREAD

**Issue by tolwan** [arjenvrh/audi_connect_ha#195]
Hi , 

Have try to install it 5 times , but every time i get NO entities ..
Is there something wrong with Audi Connect or will i make a mistake

Home Assistant 2023.8.1
Supervisor 2023.08.1
Operating System 10.4
Frontend-versie: 20230802.0 - latest

Waiting your answer
Tolwan

**Comment by QuiNz0r** [comment]
it works but you have to apply a recent fix manually until it gets updated 

see: https://github.com/arjenvrh/audi_connect_ha/issues/193#issuecomment-1666470714

**Comment by tolwan** [comment]
Thanks QuiNz0r , 

Have changed it and now i received only 1 entities ( Position ) . 
Must i change something more to get more entities ?? 

Please let me know 
Tolwan

**Comment by tolwan** [comment]
Thanks QuiNz0r ,

It Works :)   thanks again 

Tolwan

**Comment by mrechs** [comment]
After upgrading HA to 2023, I'm getting "Failed to setup" and this output in the logs... any ideas?

`  File "/config/custom_components/audiconnect/audi_services.py", line 261, in get_vehicle_information
    raise Exception("Invalid json in get_vehicle_information")
Exception: Invalid json in get_vehicle_information
 `

**Comment by archipita** [comment]
I have upgraded HA to 2023.8.2 and after the restart the integration is not working anymore. It says that the credentials are wrong.
I have seen that the myAudi app has been upgraded to v4.19. Can it be that something in the registration has been changed?

**Comment by QuiNz0r** [comment]
> I have upgraded HA to 2023.8.2 and after the restart the integration is not working anymore. It says that the credentials are wrong.
> I have seen that the myAudi app has been upgraded to v4.19. Can it be that something in the registration has been changed?

Working flawlessly for me still

**Comment by mrechs** [comment]
I’m on 2023.8.2 and getting “failed to set up”, here’s the log entry:
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 251, in get_vehicle_information
    req_rsp, rep_rsptxt = await self._api.request(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_api.py", line 75, in request
    raise TimeoutError("Timeout error")
TimeoutError: Timeout error—Matthew J. RechsOn Aug 17, 2023, at 6:53 AM, QuiNz0r ***@***.***> wrote:﻿

I have upgraded HA to 2023.8.2 and after the restart the integration is not working anymore. It says that the credentials are wrong.
I have seen that the myAudi app has been upgraded to v4.19. Can it be that something in the registration has been changed?

Working flawlessly for me still

**Comment by archipita** [comment]
Thank you for the feedbacks!
I have tried again, but left out the region field (DE) in the registration and now it is working again. Very strange.
About the errors in the logs, I have removed them modifying the files audi_entity and device_tracker as explained in the other thread.

**Comment by mrechs** [comment]
Weird. I get “invalid credentials” unless I specify US for region and I get this error in the logs:Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/__init__.py", line 111, in async_setup_entry
    return await data.update(utcnow())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 261, in get_vehicle_information
    raise Exception("Invalid json in get_vehicle_information")
Exception: Invalid json in get_vehicle_information—Matthew J. RechsOn Aug 17, 2023, at 8:22 AM, vic ***@***.***> wrote:﻿
Thank you for the feedbacks!
I have tried again, but left out the region field (DE) in the registration and now it is working again. Very strange.
About the errors in the logs, I have removed them modifying the files audi_entity and device_tracker as explained in the other thread.

**Comment by cdnninja** [comment]
Could we close this?  I assume working now.

**Comment by mrechs** [comment]
Uh, why? AFAIK it's still broken.

**Comment by cdnninja** [comment]
What region? Working for me.   Just hoping to help clean up issues.

**Comment by mrechs** [comment]
US

 [this](https://github.com/arjenvrh/audi_connect_ha/issues/197#:~:text=2%20weeks%20ago-,%23204,-I%20am%20based) seems to fix it.

**Comment by alderete** [comment]
From a longer comment on another issue, one thing that tripped me up is that I needed to re-accept the terms and conditions for Audi Connect before this integration started working again. (Even after the various fixes.)

If you think you've done everything suggested, here and elsewhere, and it's still not working, log into Audi Connect from your desktop, and make sure you've cleared that flag.
