### ISSUE TITLE
Unable to import component

### ISSUE THREAD

**Issue by rafuz** [arjenvrh/audi_connect_ha#20]
Just updated using HACS this morning and I am getting this error:

`2020-01-22 10:22:42 ERROR (MainThread) [homeassistant.setup] Setup failed for audiconnect: Unable to import component
`

I have tried reverting back to a backup and it works. I have also tried a clean install (deleted directory manually) but nothing changes.

**Comment by Hooch76** [comment]
I might be running into the same issue, not using HACS but custom_components instead.
I copied the files from git to the custom_components/audiconnect directory but get the following error when trying to configure the Audi integration (HA was restarted):

> [homeassistant.config_entries] Error occurred loading config flow for integration audiconnect: No module named 'custom_components.audiconnect.util'

**Comment by guerrerotook** [comment]
I have the same problem, I just updated the component.

**Comment by Hooch76** [comment]
Thanks for the super fast fix ... adding https://github.com/arjenvrh/audi_connect_ha/blob/master/custom_components/audiconnect/util.py solved it!
