### ISSUE TITLE
Possible to retrieve milage

### ISSUE THREAD

**Issue by pittbull** [arjenvrh/audi_connect_ha#206]
As milage is available in the app, maybe it is possible to make it available in this addon as well?

**Comment by cdnninja** [comment]
Mine shows this in home assistant already.  What region and car are you?

**Comment by pittbull** [comment]
You are indeed correct. Mine had several entities reporting "none" and milage was missing. Following your comment I just removed the integration and reloaded it - and now I too have milage. Thank you for your response.
