### ISSUE TITLE
Climatisation still won't start

### ISSUE THREAD

**Issue by tnagels** [arjenvrh/audi_connect_ha#21]
Hi Arjen,

Unfortunately, climatisation still does not start. HA logs the following message:

`Unable to start climatisation of [vin]: 400, message='Bad Request', url='https://msg.volkswagen.de/fs-car/bs/climatisation/v1/Audi/DE/vehicles/[vin]/climater/actions`
(I replaced the VIN number with [vin])

Thomas

**Comment by arjenvrh** [comment]
Hmm last weekend we got a 202 "accepted" instead of a 400. The calls were all successful, the command was rejected by the car. Apparently something has been broken during the integrating of the changes in the main code base... 

Can we setup a temporary access once more to test this?

**Comment by tnagels** [comment]
> Can we setup a temporary access once more to test this?

Sure, send me a WhatsApp to arrange this.
(Silly suggestion: I see `/climater/` in the url, the 'r' seems out of place. Could be a typo?)

**Comment by arjenvrh** [comment]
All calls seem to be in order, command is rejected by the car itself. Unclear why, it seems to be working for some other people. 

Thanks for testing with your car!

**Comment by tnagels** [comment]
Not sure if anything changed on your side, @arjenvrh , but all of a sudden the climatisation on my e-tron started working!
