### ISSUE TITLE
Failing to set up after update to commit 5bf588d (01.02.2024)

### ISSUE THREAD

**Issue by user45876** [arjenvrh/audi_connect_ha#219]
After updating to the current version (5bf588d), it is showing an error setting up. Was running fine before. Thanks for your ongoing efforts in this 👍

```
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 10:32:26 (3 occurrences)
Last logged: 10:36:03

Error setting up entry <mailaddress> for audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/__init__.py", line 111, in async_setup_entry
    return await data.update(utcnow())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 264, in get_vehicle_information
    response.parse(vins["data"])
  File "/config/custom_components/audiconnect/audi_models.py", line 186, in parse
    for item in data.get("userVehicles"):
TypeError: 'NoneType' object is not iterable
```

**Comment by BlackP999** [comment]
I have the same problem!

**Comment by euri911** [comment]
Ditto :(

**Comment by kerkyra3744** [comment]
Me too ;-(

**Comment by menloperk** [comment]
+1 How can I rollback to previous version as this is one is clearly broken!

**Comment by user45876** [comment]
You can always take the last working version and put the files into your custom components folder. 

In this case, the last known good would be here: https://github.com/arjenvrh/audi_connect_ha/tree/3b154e3e0bf0a273b9856f7e5b27018f34a5cfe4

**Comment by M4v3r1cK87** [comment]
+1

**Comment by menloperk** [comment]
Maybe easier for the owner to revert today's commits in github so we can redownload...

**Comment by Prash1407** [comment]
had the same issue, thanks @user45876 for the workaround for now until its fixed

**Comment by cdnninja** [comment]
Is the theory this was the URL change?

**Comment by Prash1407** [comment]
It could be, I had a look at the recent changes, and it looks like apart from a bit of clean-up, the change or URL could have caused to break the integration, saw you have already made the change and send a pull request, have you tried the change locally and has it fixed the issue?

**Comment by Prash1407** [comment]
All working fine here in CH with the latest update, might be worth to change over to vX.XX layout for update to make it user friendly.

**Comment by Prash1407** [comment]
@cdnninja [dc6abae](https://github.com/arjenvrh/audi_connect_ha/commit/dc6abaea53cdecff0696cb3a6aeb0ebc5232dcf9) caused the integration to break again for some reason

**Comment by cdnninja** [comment]
Could you create a pull request for the issue you have? Or provide the logs?
