### ISSUE TITLE
Last update 5bf588d - Error setting up entry - Configuration failed

### ISSUE THREAD

**Issue by M4v3r1cK87** [arjenvrh/audi_connect_ha#220]
Hello everyone,
I've updated the HACS package to the latest version (5bf588d) but when I've restarted Home Assistant, the package not working anymore (configuration failed).

The log report this error:

Logger: homeassistant
Source: custom_components/audiconnect/audi_models.py:186
Integration: Audi Connect (documentation, issues)
First occurred: 11:10:13 (6 occurrences)
Last logged: 11:13:15

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 112, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 264, in get_vehicle_information
    response.parse(vins["data"])
  File "/config/custom_components/audiconnect/audi_models.py", line 186, in parse
    for item in data.get("userVehicles"):
TypeError: 'NoneType' object is not iterable

I've tried also to reconfigure the package, but the same error appear (Configuration failed) and nothing appears under devices and entities.

**Comment by menloperk** [comment]
+1

**Comment by user45876** [comment]
Same as https://github.com/arjenvrh/audi_connect_ha/issues/219

**Comment by AlexMPopov** [comment]
+1

**Comment by cdnninja** [comment]
Closing as duplicate.
