### ISSUE TITLE
Skoda / VolksWagen support

### ISSUE THREAD

**Issue by jaxer** [arjenvrh/audi_connect_ha#23]
Thanks for great component!

Sad that it does not support my Skoda.

I did looked into it a bit, seems that Skoda implementation is very similar. It has a bit different login procedure but not much more than that.

Example of universal implementation of similar component (which partly works for my car): https://github.com/TA2k/ioBroker.vw-connect/blob/master/main.js 

Would you like to change implementation into something more generic? I.e. remove audi_ from file names and add ability to change some services based on vendor.
I might be able to help with Skoda specifics.

**Comment by jaxer** [comment]
see https://github.com/arjenvrh/audi_connect_ha/pull/24

**Comment by arjenvrh** [comment]
Due to lack of testing capabilities (no one wants to buy me a new Skoda or VW 😃) I'm closing this for now.
