### ISSUE TITLE
Only 4 Entitys

### ISSUE THREAD

**Issue by SirDonW** [arjenvrh/audi_connect_ha#234]
Hello,

I have take the Update and at this time, i have only 4 entitys.

Have any the same Problems?

![IMG_0323](https://github.com/arjenvrh/audi_connect_ha/assets/159892493/0a280f65-7b6e-4381-b392-1a74fc4d7be9)

Best regards

**Comment by nobirdnobird** [comment]
Same 4 me.
![Screenshot_20240303_190106](https://github.com/arjenvrh/audi_connect_ha/assets/42351982/d751fb94-4bc4-4baa-8f58-111b25d4ee26)


PS: Thanks 4 patching 🙏👍

**Comment by martale76** [comment]
Same issue for my 2022 car 45 TFSI A6

**Comment by DivingUp** [comment]
please check the newest version

**Comment by nobirdnobird** [comment]
After reloading hacs I could update to the newest version. After that there was 5 entities shown. So I tried to reinstall the module. After login there where again only 4 entities shown.

**Comment by nobirdnobird** [comment]
![Screenshot_20240304_153643](https://github.com/arjenvrh/audi_connect_ha/assets/42351982/f25274c8-d531-44c7-b6ef-9a2b4d82fdf3)

**Comment by sebadv** [comment]
Latest main version, same issue
![image](https://github.com/arjenvrh/audi_connect_ha/assets/23437866/b96e77a9-d648-4dcf-894c-53d6a2227f1d)

**Comment by nobirdnobird** [comment]
Updated today. Unfortunatly same result. 
Do I have to entere the S-ID ? 

![Screenshot_20240305_110713_io homeassistant companion android_edit_61004314941211](https://github.com/arjenvrh/audi_connect_ha/assets/42351982/6eac5820-237e-4cf2-99d8-8bf9079b8f30)
![Screenshot_20240305_110838_io homeassistant companion android_edit_60988529528713](https://github.com/arjenvrh/audi_connect_ha/assets/42351982/df85406e-3404-4ef6-a432-2494643619f8)

**Comment by Kolbi** [comment]
Should be fixed?

**Comment by SirDonW** [comment]
Yes, i have take at this time the newest Update. Its all fine.

Big thanks for patching!

Best regards

**Comment by DivingUp** [comment]
> Should be fixed?

Yes

**Comment by nobirdnobird** [comment]
Fixed 👏👏👏👏🙏🙏🙏🙏🙏

![Screenshot_20240305_193921](https://github.com/arjenvrh/audi_connect_ha/assets/42351982/7feaed3f-bc4c-46a7-9c36-30df1dc4ba2f)

**Comment by nobirdnobird** [comment]
Fixed 👏👏👏👏👏👏🙏🙏🙏🙏🙏

![Screenshot_20240305_193921_edit_64210124868847](https://github.com/arjenvrh/audi_connect_ha/assets/42351982/61c6f1f0-d609-4dd2-bbd3-65d192d1980f)
