### ISSUE TITLE
 Data is missing even after updating the integration

### ISSUE THREAD

**Issue by tomasenskede** [arjenvrh/audi_connect_ha#236]
I just returned from a seven-day skiing adventure, and my vehicle is in dire need of charging. Regrettably, my Home Assistant is failing to display any information related to my car. I noticed an update was available, which I promptly installed, followed by a restart of Home Assistant, but the problem remains unresolved.

Curiously, the MyAudi app along with the website (https://my.audi.com/) are both showing current details about my vehicle.

Does anyone have suggestions on how to access the State of Charge (SOC) data so that my charging algorithm can resume control and initiate the charging process once more?

**Comment by Ingrimmsch93** [comment]
Audi shutdown the old API, so the integration needs to be updated.
We have a first update, so we get data with the new API.
Unfortunatly the data structure seems to be not the same. Some users have all/nearly all values, some have less.
If i understand it correctly, then  https://github.com/arjenvrh/audi_connect_ha is working well for full EV or non electric cars. Hybrids seems to have issues. For me (hybrid) the current version of t0bias-r gives me most values: https://github.com/t0bias-r/audi_connect_ha/tree/master
Charging state and plug state is working for me. Charging mode is not working and shows "unsupported"

So try one or the other or wait for the next (hopefully with less "bugs") release.

**Comment by cdnninja** [comment]
A few people are working on it.   Should improve with time.  Other forks exist as well.  I'm hoping we can bring it together here.

**Comment by DivingUp** [comment]
> I just returned from a seven-day skiing adventure, and my vehicle is in dire need of charging. Regrettably, my Home Assistant is failing to display any information related to my car. I noticed an update was available, which I promptly installed, followed by a restart of Home Assistant, but the problem remains unresolved.
> 
> Curiously, the MyAudi app along with the website (https://my.audi.com/) are both showing current details about my vehicle.
> 
> Does anyone have suggestions on how to access the State of Charge (SOC) data so that my charging algorithm can resume control and initiate the charging process once more?

Thanks for the tip.
Audi has changed and deactivated a lot on your site.
Basically, however, you should not make the availability of your car dependent on the function of an HA app that is currently no longer maintained by the owner.... we are currently patching on the side... as best we can.

**Comment by cdnninja** [comment]
Please try latest.

**Comment by tomasenskede** [comment]
I've updated the integration, and now it's functioning again! Thanks a lot!

![image](https://github.com/arjenvrh/audi_connect_ha/assets/32595351/8b47c392-93c0-4f6e-8c55-d00c4f8eefb5)
