### ISSUE TITLE
Shortterm and logterm data causes account issues

### ISSUE THREAD

**Issue by gangemij** [arjenvrh/audi_connect_ha#251]
This is something that I was working on a while ago and had commented the lines from the audi_connect_account.py file. The pulling of these values cause 403 errors. I would like to create a branch and then PR to comment these. 
Lines 404-407
            #info = "shortterm"
            #await self.call_update(self.update_vehicle_shortterm, 3)
            #info = "longterm"
            #await self.call_update(self.update_vehicle_longterm, 3)

Is it possible to make these updates to the master or allow a branch creation. 

You can refer to previous issue: #213

**Comment by cdnninja** [comment]
You can create a fork and a pull request from that.  It will give you full control that way.

**Comment by t0bias-r** [comment]
@cdnninja We could add something similar to `support_preheater` variable/check...? If 403 or 502 is returned, preheater won't be queried anymore. Same could be done for tripdata

**Comment by gangemij** [comment]
Yes that would work perfectly. I haven’t tested the WebAPI to see if the behaviour is different but having it automatically excluded the value would make sense.

**Comment by Kolbi** [comment]
Mentioned here: https://github.com/arjenvrh/audi_connect_ha/pull/249#issuecomment-1978165202

**Comment by gangemij** [comment]
This issues is covered in #249
