### ISSUE TITLE
Unable to Un/Lock car from Hassio

### ISSUE THREAD

**Issue by Bosken85** [arjenvrh/audi_connect_ha#28]
Whenever i hit the Un/Lock button it doesn't work and the logs show 2020-04-17 17:01:09 ERROR (MainThread) [custom_components.audiconnect.util] Unable to unlock "{secret vinn number}": invalid literal for int() with base 16: 'wa'

**Comment by arjenvrh** [comment]
Are you sure the spin is correct?

**Comment by JamieP83** [comment]
adding quotes worked for me

`service: audiconnect.execute_vehicle_action
data:
  vin: 'xxx'
  action: 'unlock'`
