### ISSUE TITLE
GPS position shows not_home

### ISSUE THREAD

**Issue by CanD42** [arjenvrh/audi_connect_ha#3]
I have integrated Audi connect into HA without a problem. Thanks for that.
I noticed a glitch that the car device tracker device_tracker.audi_* is showing not_home. I think this is because the coordinates have to be in a format. In configuration.yaml I have for instance latitude: 52.4 but in the device tracker I see latitude: 524xxxxx without the dot. Can you please convert the latitude and longitude?

BTW: Can more attributes like the gas percentage be also added?

Thanks,
Daniel

**Comment by arjenvrh** [comment]
Thanks for reporting the issue with the position, corrected it. 
Tank level and hood status attributes have also been added

Regards
Arjen
