### ISSUE TITLE
Support folding top (convertible)

### ISSUE THREAD

**Issue by wmalgadey** [arjenvrh/audi_connect_ha#30]
Thank you very much for this integration. I did start my own, but didn't finish it to this level because of busy working days :(

Would it be possible to add support for the state of the folding top? I have only a german account, but it is available in webview and in the app:

![image](https://user-images.githubusercontent.com/141838/80793584-d3535d80-8b97-11ea-97a9-f29a471555a3.png)

**Comment by arjenvrh** [comment]
If you can find out which of the properties contains this info and which values correspond to open and closed, I'd be happy to add it. As my top doesn't fold I can only guess. :-)

You could add a print statement in audi_connect_account.py in the function update_vehicle_statusreport() to get the full result of the call to self._audi_service.get_stored_vehicle_data. One of the fields is probably the one you want.

**Comment by wmalgadey** [comment]
Thanks for the hint! I will look what I can do. The component looks complicated, tried to get a head of it, but have been busy since.

Do you know if somebody maybe did "refactor" the web ui? It seems to use a different API?

**Comment by arjenvrh** [comment]
Closing this for now, when someone can provide me with the information I'd be happy to add it
