### ISSUE TITLE
Location Error (but still kind of working)

### ISSUE THREAD

**Issue by monsieurlatte** [arjenvrh/audi_connect_ha#31]
Anyone else seeing this in their logs?  

Unable to update the vehicle position of WAUvinremvoed: 204, message='No Content', url='https://msg.volkswagen.de/fs-car/bs/cf/v1/Audi/US/vehicles/WAUvinremoved/position

**Comment by arjenvrh** [comment]
I get that occasionally too, sometimes all seems well but we get no info back from audi.
