### ISSUE TITLE
Add brand images to home assistant

### ISSUE THREAD

**Issue by denniswham** [arjenvrh/audi_connect_ha#32]
In the recent version of Home Assistant brands (logos) of integrations are shown when adding new or view details - home-assistant/frontend#5500
It would be awesome to see the Audi logo there.
More info: https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/

**Comment by arjenvrh** [comment]
Added pull request at https://github.com/home-assistant/brands/pulls

**Comment by arjenvrh** [comment]
Pull request has been accepted, images should be up shortly

**Comment by denniswham** [comment]
Thanks Arjen!
