### ISSUE TITLE
Tank Level

### ISSUE THREAD

**Issue by KayGt3** [arjenvrh/audi_connect_ha#34]
Hello,

the Tank level is stuck to 100%. All the other sensor is working fine.

Thanks!

**Comment by arjenvrh** [comment]
Strange, it's still working for me. I assume tank level is reporting ok on the audi website?

**Comment by KayGt3** [comment]
Sorry for my late reply, unfortunately with my car (Audi A3 e-tron) i can't read the tank level.

Thanks again!
