### ISSUE TITLE
Only showing 1 entity (name, model of the car)

### ISSUE THREAD

**Issue by asemev** [arjenvrh/audi_connect_ha#37]
Hi team, just installed Audi connect on a brand new Home Assistant installation. The Audi connect integration finds only 1 entity (name, model etc).  I have another raspberrypi with home assistant and there all works well and I see 21 entities. Any idea what i'm doing wrong?

Log Details (WARNING)
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:443
First occurred: 1:42:31 AM (1 occurrences)
Last logged: 1:42:31 AM

Entity sensor.audi_a6_avant_model is incorrectly being triggered for updates while it is disabled. This is a bug in the audiconnect integration.

**Comment by tnagels** [comment]
I seem to have the same problem. I removed the integration from my HA for a while and now did a clean re-install. As a result I also get only one sensor (car model).

**Comment by tnagels** [comment]
**I resolved this for my installation**

I had created a separate user in myAudi for my Home Assistant. However, after changing the Pin, the primary user of the car has to re-confirm access for the other user. Once I re-confirmed, a reboot of Home Assistant showed all the sensors.

So, my advice is: log in to my Audi as the primary user and check that the user you have for Home Assistant is active.
