### ISSUE TITLE
Questions regarding interval config

### ISSUE THREAD

**Issue by jacquesvzijp** [arjenvrh/audi_connect_ha#38]
Hi, really like this component and it works perfectly. I used default refresh interval at setup but would like to change it now. Is there a way to do so? Ideally I modify it dynamically or use the refresh service triggered by an external event (I failled to get the right syntax since I guess I am too newbie), i undertand something with VIN is missing...

type: button
tap_action:
  action: call-service
  service: audiconnect.refresh_vehicle_data
hold_action:
  action: more-info
show_icon: true
show_name: false
entity: input_boolean.get_car_update

**Comment by jacquesvzijp** [comment]
Hi, second part already solved, I can successfully use the refresh service now. Only remains the question to change the regular interval. Thanks!

**Comment by arjenvrh** [comment]
All settings are saved together upon installation, only way currently is to remove & reinstall the integration...
