### ISSUE TITLE
First Install Not Seeing Sensors

### ISSUE THREAD

**Issue by monsieurlatte** [arjenvrh/audi_connect_ha#4]
I live in North America, I see that you say we need a region but dont give an example, I tried using region: na but I am not seeing any sensors, also not seeing any errors in the log, what's the best way to trouble shoot this?

**Comment by arjenvrh** [comment]
It seems the API is not working for US and CN. Someone from these regions will have to look if he/she can modify David's library (davidgiga1993/AudiAPI) and get it working. In the meantime I'll update the documentation.
