### ISSUE TITLE
Login has changed after maintenance (no longer works)

### ISSUE THREAD

**Issue by shuntfield** [arjenvrh/audi_connect_ha#40]
It would seem that Audi has changed the login over the last maintenance period, and the integration is no longer able to login.

```
Log Details (ERROR)
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:93
Integration: Audi Connect (documentation)
First occurred: August 10, 2020, 8:19:13 AM (777 occurrences)
Last logged: 6:35:25 AM

Login to Audi service failed, trying again in 10 seconds
Login to Audi service failed: 400, message='', url='https://id.audi.com/v1/token
```

Everything was fine with my car yesterday, but today after the maintenance I can no longer login, incidentally when I attempt to login via myAudi, the login is different and after the maintenance the existing session was logged out, with a session expired message.

I guess that is what is causing this on login attempts.

![audi connect](https://user-images.githubusercontent.com/63152393/89861909-b79c2200-db9e-11ea-9adb-64e869811fa7.png)

Up until today, it has worked flawlessly for me, (albeit with trouble caused only by me!)

Hope this helps

Shunts...

**Comment by jacquesvzijp** [comment]
Hi
Same here. Indeed they announced a large update and it seems the integration no longer works;-( pitty .
Jacques

**Comment by kevincroughs** [comment]
Same here

**Comment by typendetinus** [comment]
Had the same thing happen to me I am afraid

**Comment by shuntfield** [comment]
Thanks for everyone confirming as well. It seems that the new audi login goes via some VW portal now. You get the same data but the login is different. If you go to myAudi, it redirects you.

![myaudi1](https://user-images.githubusercontent.com/63152393/90013857-fb298580-dc9d-11ea-9890-46e4db4a7ad4.JPG)
![myaudi2](https://user-images.githubusercontent.com/63152393/90013860-fd8bdf80-dc9d-11ea-9319-386c0ff5ffd7.JPG)


Shunts...

**Comment by 6jw** [comment]
Same 🥺

**Comment by Whippie72** [comment]
I think it is related to this message, which I unfortunately only have in German.
Between the 07.08. and 12.08.2020 technical further developments were carried out at the myAudi system world.

![IMG_3649](https://user-images.githubusercontent.com/65712131/90220502-9b9bb900-de08-11ea-8507-a19107031b61.PNG)

**Comment by shuntfield** [comment]
Yeah, that's more or less what it says in English, no login, no login and registration, then no vehicle login, on the 07-12 August.
It seems. Audi transferred the login to a new platform this is why  it no longer works. 🙁

**Comment by typendetinus** [comment]
It looks like they locked their old authentication system after moving over to the new one, it's still alive but refusing logins or so it seems

**Comment by shuntfield** [comment]
> It looks like they locked their old authentication system after moving over to the new one, it's still alive but refusing logins or so it seems

Yeah I agree, I've had a look at the code, but I'll not pretend  that I know what I am doing!

The new login goes via a VW type site, funnily enough it's also the same portal entry for Audi Finance in the UK.

**Comment by korsmann** [comment]
I see the same issue. Hopefully there is a fix for this. Removed this from HA for now.

**Comment by shuntfield** [comment]
> I see the same issue. Hopefully there is a fix for this. Removed this from HA for now.

I have done the same

**Comment by MarcelD1973** [comment]
Same overhere. Look likes it comes because the server changed from audi.com to vwgroup.io. 
Maybe @arjenvrh can fix that very easy in the systemfiles with an update.

**Comment by antoinevandenhurk** [comment]
Same issue over here! 
I miss the confirmation from HA that the doors are locked before I go to sleep...

**Comment by shuntfield** [comment]
> Same issue over here!
> I miss the confirmation from HA that the doors are locked before I go to sleep...

Yes me too, I had an auto that locked the car if the doors were unlocked and the sun was down or the temperature drops, if my car was on my drive.

Was pretty useful.

**Comment by arjenvrh** [comment]
Yeah I'm aware of the issue, however, it seems that the login procedure has changed, not just the url. My time for reverse engineering the new login is quite limited, so if someone has more info it is much appreciated.

**Comment by pergolafabio** [comment]
Hey...

Someone on community forum, posted the json output from Android app, maybe that's useful? It's in latest reply

**Comment by tmooz** [comment]
Audi changed the API. 👎 
@shuntfield is there any possibilty that your are going to have a look at this?

**Comment by shuntfield** [comment]
> Audi changed the API. 👎
> @shuntfield is there any possibilty that your are going to have a look at this?

Sorry friend, I don't have the abilities to to that, I know a little bit of coding but not enough to resolve the problem.

It does look like some people are working on the audiAPI though perhaps that will come across to Audi Connect.

**Comment by tmooz** [comment]
@arjenvrh the question was for you, 'is there any possibilty that your are going to have a look at this?'  .. sorry @shuntfield ;-)

**Comment by pergolafabio** [comment]
see here , allthough if fixed, not sure how to implement it in this custom ?

https://github.com/davidgiga1993/AudiAPI/issues/13

**Comment by shuntfield** [comment]
> see here , allthough if fixed, not sure how to implement it in this custom ?
> 
> [davidgiga1993/AudiAPI#13](https://github.com/davidgiga1993/AudiAPI/issues/13)

I'm not 100% sure but I think this Audi Connect is built up on the AudiAPI.

Given my limited experience with coding I'll have a look.

**Comment by pergolafabio** [comment]
yeah, so this code needs to be changed too, its just not like a new "audiapi" release

**Comment by arjenvrh** [comment]
This Integration was originally using the audiapi library, however, last time Audi changed everything there seemed to be little activity there and I had to completely rewrite both the login and all requests. 

As has been noted before, the login mechanism changed completely and it is much more than simply swapping urls. 

As I currently don’t have access to an android phone, it is hard to reverse engineer the app. However, it seems that davidgiga1993 from the audiapi lib has the new login working now in a testing branch. I’ll try to find some time next week to test this and try to integrate it.

**Comment by pergolafabio** [comment]
Appreciated!!!

**Comment by asemev** [comment]
Big thank you!

**Comment by shuntfield** [comment]
> This Integration was originally using the audiapi library, however, last time Audi changed everything there seemed to be little activity there and I had to completely rewrite both the login and all requests.
> 
> As has been noted before, the login mechanism changed completely and it is much more than simply swapping urls.
> 
> As I currently don’t have access to an android phone, it is hard to reverse engineer the app. However, it seems that davidgiga1993 from the audiapi lib has the new login working now in a testing branch. I’ll try to find some time next week to test this and try to integrate it.

That's great news thanks 👍

**Comment by antoinevandenhurk** [comment]
That would be awesome 😃

Op za 12 sep. 2020 11:51 schreef shuntfield <notifications@github.com>:

**Comment by FrankBakkerNl** [comment]
The website also uses a REST api. Not sure if it is the same API and login mechanism that is used by the app. I tried to replicate the login process from the website in Postman but was not succesfull so far. Maybe someone else is able to reverse enginere the login that is used in the browser, I think that would be easier than from the app on Android.

**Comment by mcfly76** [comment]
@arjenvrh That would be awsome! Thanks for your effort!

**Comment by arjenvrh** [comment]
I've updated the login with the infos that the audiapi guys found in the thread mentioned by @shuntfield. Please try it and report back here in case of any issues. 

The login has become a soup of redirects and queries, only time will tell how stable the integration will run as a consequence. I might add token refreshing to support more regular updates. 

The good news is that all else seems to be the same, I've even been able to lock the car using the tokens obtained during the login procedure.

**Comment by asemev** [comment]
Hi, i just tried and it still doesn't work and gives the error:  Invalid
credentials

**Comment by arjenvrh** [comment]
Have you accepted the new terms of use in the app / website?

**Comment by shuntfield** [comment]
> Have you accepted the new terms of use in the app / website?

@arjenvrh I'm out of the house at the moment but I will test at the first opportunity 🙂

**Comment by pergolafabio** [comment]
yes, for me it works, but only 1 sensor created? is that possible?


sensor.audi_a4_avant_model | Audi A4 Avant sport 2.0 TDI 110(150) kW(PS) S tronic | model: Audi A4 Avant sport 2.0 TDI 110(150) kW(PS) S tronic/Audi A4 Avant model_year: 2018 model_family: Audi A4 Avant title: Audi A4 Avant csid: xxx vin: xxx friendly_name: Audi A4 Avant Model icon: mdi:car-info assumed_state: true
-- | -- | --

**Comment by typendetinus** [comment]
Can confirm that it works over here, I have all the sensors again
After recreating/reinstalingl the integration. Evertyhing works again

Excellent job!!!

**Comment by pergolafabio** [comment]
ok, works here also , i now created without the s-pin / region, not needed for europe
also 18 sensors up and running now :)

**Comment by mackay2k4** [comment]
works like a charm for me. 
Thanks @arjenvrh

**Comment by tmooz** [comment]
GREAT!!

@arjenvrh let me buy you a beer! Thanks so much!

**Comment by Hooch76** [comment]
I get the following error after restarting Home Assistant.
Any tips? 
```
[homeassistant.setup] Setup failed for audiconnect: Unable to import component: No module named 'bs4'
```

**Comment by shuntfield** [comment]
@arjenvrh yep all appears working here too job many thanks!
I'm using HACS so had to completely remove it and reinstall it for it to work but other than that fine.

**Comment by jacquesvzijp** [comment]
Great, it works again, thanks a lot!!! Both cars show up with all entities.

**Comment by korsmann** [comment]
> I've updated the login with the infos that the audiapi guys found in the thread mentioned by @shuntfield. Please try it and report back here in case of any issues.
> 
> The login has become a soup of redirects and queries, only time will tell how stable the integration will run as a consequence. I might add token refreshing to support more regular updates.
> 
> The good news is that all else seems to be the same, I've even been able to lock the car using the tokens obtained during the login procedure.

Works great now, so far.

Thanks for teh effort!

**Comment by shuntfield** [comment]
As @arjenvrh has fixed the login, then I shall close the case.
Bought you few beers too 😉

**Comment by arjenvrh** [comment]
Good to hear it works! Thanks for all the feedback and many thanks to @shuntfield and @tmooz for the beers, I'll try not to drink them all at once! 😃
