### ISSUE TITLE
Unable to import component: No module named 'bs4'

### ISSUE THREAD

**Issue by Hooch76** [arjenvrh/audi_connect_ha#41]
I just wanted to add the updated integration (thanks a lot!) to Home Assistant, but I get the following error after restarting Home Assistant:

```
[homeassistant.setup] Setup failed for audiconnect: Unable to import component: No module named 'bs4'
```

When trying to add the integration using the Home Assistant GUI it says

```
[homeassistant.config_entries] Error occurred loading configuration flow for integration audiconnect: No module named 'bs4'
```

Thanks

**Comment by asemev** [comment]
I managed to make my connection also work! Had to update HACS. It informed
me Audi Connect needs an update. And right after the login worked perfectly.

THANK YOU!!!

**Comment by Hooch76** [comment]
I fixed it by installing **bs4** in my Python virtual environment. 
You might want to add it to https://developers.home-assistant.io/docs/creating_integration_manifest/ so that it gets installed automatically (if this works for custom components, too).

**Comment by arjenvrh** [comment]
Added the dependency to the manifest
