### ISSUE TITLE
Issue: Getting auth failures after recent update to fix auth failures.  :)

### ISSUE THREAD

**Issue by heymoe** [arjenvrh/audi_connect_ha#43]
Looks like the recent update to fix logging into Audi Connect for non-US(?) users (https://github.com/arjenvrh/audi_connect_ha/issues/40) broke my ability to login to Audi Connect. Up until this latest update, everything was working fine.

I applied the update via HACS, restarted HA and the integration failed to pull any information for my car. I deleted the integration for HA and deleted this component from HACS then re-installed it fresh via HACS. Restarted HA and then went to add the integration back to HA. I filled in all the info, hit submit and then received an auth failure message. 

I reverted back to the [b85121a](https://github.com/arjenvrh/audi_connect_ha/tree/b85121a4efc8dfdc5663aa2e4ddccde4e72e79c0 ) commit from May 26, 2020 by manually removing the latest version HASC installed in the custom_components folder and copying b85121a files in place. Reboot HA and then re-added the integration in HA and this time after submitting my information it worked. No auth issues and my status card for my car is showing information once again.

**Comment by arjenvrh** [comment]
The integration now should switch to the old login method when region is set to US. Please let me know if it works.

**Comment by heymoe** [comment]
Installed the update and everything looks to be working. I don't like that there has to be a hard-coded exception to work around this since it will eventually break when the US gets upgraded to the v2 login method. At least it looks like a quick code change when that time comes.

Thanks for the update!

**Comment by arjenvrh** [comment]
I also don't like the hard-coded exception, but it's the easiest fix for now and making the login procedure an integration parameter is probably also not a great idea in terms of usability. When the login method is changed for the US, the fix is very easy, under the assumption that the new login is the same as the one in Europe of course.
