### ISSUE TITLE
Login Failing "Invalid Credentials"

### ISSUE THREAD

**Issue by shuntfield** [arjenvrh/audi_connect_ha#48]
Hello
It seems that something isn't working again:

![halogin](https://user-images.githubusercontent.com/63152393/96614997-a7b86100-12f8-11eb-83cd-19fb7e5807ee.png)

It stopped working this afternoon.

I can login with the Audi App on my phone, but not Home Assistant.

I had removed and reinstalled the integration before all my entities were unavailable up until I reinstalled it, now I cannot log in.

I think it may be something to do with home assistant generally though because at the same time my colleagues BMW connected drive has started doing the exact same thing. Could it be some kind of authentication error globally on Home Assistant?

https://github.com/home-assistant/core/issues/42139

I don't seem to be able to get the logs from my HA to be able to post them, from earlier.

Thanks

Shunts...

**Comment by duckend** [comment]
Seeing the same behaviour (UK to help identify login server). The integration polls started failing with 403 errors yesterday morning.

**Comment by shuntfield** [comment]
Also UK here.
I wasn't able to see what happens because I uninstalled and reinstalled the integration and it cleared the logs out. I can't login anymore now.

**Comment by mjspuk** [comment]
Same problem and timings here (also UK). Extract from the most recent failed connection: 

2020-10-21 09:21:27 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2020-10-21 09:21:43 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 403, message='Forbidden', url=URL('https://app-api.my.audi.com/myaudiappidk/v1/token')

**Comment by typendetinus** [comment]
NL over here, same thing is happening over here. 403 error.
But the Audi app is working fine. 

Maybe they blocked the client_id ?

**Comment by shuntfield** [comment]
There was an update to this today, installed it but still no change, it still says "invalid credentials" when logging in, as previously mentioned, I removed and reinstalled the integration when it wasn't working.

**Comment by mbuzina** [comment]
Just wanted to log on to my new audi connect - I have the same issue (Germany). Error is "Ungültige Anmeldeinformationen" or "invalid credentials". I have tried to find something in the log as well, but nothing there.

**Comment by vBrolin** [comment]
> There was an update to this today, installed it but still no change, it still says "invalid credentials" when logging in, as previously mentioned, I removed and reinstalled the integration when it wasn't working.
That update was for my pull request for preheating switch
https://github.com/arjenvrh/audi_connect_ha/pull/47

It was requested before this failed and is not related.

**Comment by shuntfield** [comment]
> > There was an update to this today, installed it but still no change, it still says "invalid credentials" when logging in, as previously mentioned, I removed and reinstalled the integration when it wasn't working.
> > That update was for my pull request for preheating switch
> > #47
> 
> It was requested before this failed and is not related.

Yeah, I did see that afterwards 🙂, is yours able to log in?

**Comment by 6jw** [comment]
Same here (NL) - stopped working with 403 Forbidden. Removed integration, can't add integration due to Invalid Credentials.

**Comment by vBrolin** [comment]
> Yeah, I did see that afterwards 🙂, is yours able to log in?

No I got the same issue. Its the same for everyone.

**Comment by FilippoS1973** [comment]
Same here Italy. Invalid credentials

**Comment by titiviking** [comment]
Same here (BE). Invalid credentials

**Comment by antoinevandenhurk** [comment]
Can someone figure this out please... I am missing my HA notification that my Etron is fully loaded!

**Comment by Maffewem** [comment]
Haven't previously used this module but encountered the login error upon installation, can see it's a wider issue (UK).

**Comment by duckend** [comment]
Some progress being made here... [https://github.com/davidgiga1993/AudiAPI/issues/13#issuecomment-715466623](url)

**Comment by mbuzina** [comment]
Link duckend posted does not work (for me), but I guess it is this issue : https://github.com/davidgiga1993/AudiAPI/issues/13

Seems to contain the solution (a signed timestamp and a changed endpoint to get the token).

**Comment by pergolafabio** [comment]
> Link duckend posted does not work (for me), but I guess it is this issue : [davidgiga1993/AudiAPI#13](https://github.com/davidgiga1993/AudiAPI/issues/13)
> 
> Seems to contain the solution (a signed timestamp and a changed endpoint to get the token).

Any idea how to change that in our custom component ?

**Comment by andig** [comment]
You can find a working implementation in my EV Charge Controller: https://github.com/andig/evcc/blob/master/vehicle/audi.go. Hope this helps...

**Comment by pergolafabio** [comment]
i think maybe line 448 needs a change? allthough it looks correct in this file : ?? 
https://github.com/arjenvrh/audi_connect_ha/blob/master/custom_components/audiconnect/audi_services.py

```
        data = {
            "client_id": "mmiconnect_android",
            "scope": "openid profile email mbb offline_access mbbuserid myaudi selfservice:read selfservice:write",
            "response_type": "token id_token",
            "grant_type": "password",
            "username": user,
            "password": password,
        }
```

**Comment by shuntfield** [comment]
I have just updated mine and it seems to be working now, great work! I'll keep this issue open for a day or so to keep track of any changes and then close it.

**Comment by typendetinus** [comment]
Works like a charm again over here.

Many thanks!!!
