### ISSUE TITLE
problem of integration

### ISSUE THREAD

**Issue by pilot1981** [arjenvrh/audi_connect_ha#53]
Hi,
I have HASSIO 0.117.2; I installed this integration using HCAS, but now I don't it in HACS and if I go to:

Configuration->Integrations, click + and search for Audi Connect

I don't found anything...

you can help me?

**Comment by pilot1981** [comment]
integration appeared itself after few minutes...

**Comment by pilot1981** [comment]
Hi,
I don’t understand where I can find S-PIN...you have another name for this?

Where I can check if it’s right?

AUDI blocked my PIN for too many errors...how I can unlock it?

**Comment by mjspuk** [comment]
I had the same problem setting up - couldn't figure out what the S-PIN was - and now I can't be sure I remember what I figured it out to be. Try in the myAudi app > All equipment details; I think it was the 8-digit number under "Audi connect".

**Comment by pilot1981** [comment]
I tried 8-digit number found under my Audi connect app, but Audi locked again...I think this isn't right S-PIN...

any suggestion to try to find it?

**Comment by jamiefiedler** [comment]
> I tried 8-digit number found under my Audi connect app, but Audi locked again...I think this isn't right S-PIN...
> 
> any suggestion to try to find it?

S-PIN is the 4 digit code you would enter when locking/unlocking via the mobile app.

In the myAudi app, go here to confirm/change/reset if needed:
Profile -> Account settings -> PIN -> Change PIN / Forgot PIN

**Comment by pilot1981** [comment]
Thanks. Solved
