### ISSUE TITLE
No informations for e-tron

### ISSUE THREAD

**Issue by MrKrautwurst** [arjenvrh/audi_connect_ha#57]
Hey,
I have a SQ7 and everthing is fine, but the only information I get for the etron 2021 is the vehicle type.
I don't get any information about battery status, windows, etc.

Any ideas?

Thanks

**Comment by plh4** [comment]
Same issue here :/ 
Got only a function to (un)lock the doors.

**Comment by arjenvrh** [comment]
Should be fixed with #50
