### ISSUE TITLE
Cannot find Audi Integration (after HACS custom component installation and reboot/restart)

### ISSUE THREAD

**Issue by asemev** [arjenvrh/audi_connect_ha#58]
Hi, first of all big thanks for this integration. I love it and use it all the time. Well i used to.
I moved to a new raspberry pi setup and rebuilt everything from scratch.
I just cant find the Audi Connect integration.
Any idea why this could be happening?
Thx!

![image](https://user-images.githubusercontent.com/30929896/103388290-8948c000-4b08-11eb-8bd9-25ebba661631.png)

![image](https://user-images.githubusercontent.com/30929896/103388296-92d22800-4b08-11eb-8abb-8ae86d670e94.png)

**Comment by MrKrautwurst** [comment]
First reboote HA & clean the cache of your browser or restart the app.
Then you can find it in the integrations and install it.

**Comment by asemev** [comment]
Thank you very much. It worked.
