### ISSUE TITLE
charging power and charging rate not updated

### ISSUE THREAD

**Issue by jtonk** [arjenvrh/audi_connect_ha#59]
charging power and charging rate status remain unavailable when the car is plugged in. However when I restart HA (and the car is charging) the status of the charging power and charging rate is updated. 

I didn't look into the code yet, but it appears that you need to fetch charging power and charging rate when the "charging state" has changed to "charging". 

Any idea how this can be improved?

**Comment by arjenvrh** [comment]
See the readme:

**audiconnect.refresh_vehicle_data**
The normal update procedure retrieves the data from the servers and does not directly interact with the vehicle. This service triggers an update request from the vehicle. When the data is retrieved successfully, the data in Home Assistant is automatically updated. The service requires a vin as parameter."
