### ISSUE TITLE
Windows icon in blue

### ISSUE THREAD

**Issue by asemev** [arjenvrh/audi_connect_ha#61]
Hi guys, any idea why my windows icon shows in blue color? It's a binary sensor. Could that be the reason? My integration only gives me a binary sensor for the windows. Not a normal sensor. Thanks a lot.

![Screenshot_20210105-194854_Home Assistant](https://user-images.githubusercontent.com/30929896/103686440-21262e00-4f8f-11eb-8278-10e60ab88745.jpg)

![Screenshot_20210105-194906_Home Assistant](https://user-images.githubusercontent.com/30929896/103686454-25eae200-4f8f-11eb-998d-dcd514ccc6bc.jpg)

**Comment by insert10p** [comment]
Not sure. Here's a screenshot of mine and snippet of config:
![image](https://user-images.githubusercontent.com/24699660/103714241-18951e00-4fb6-11eb-81c5-c28dc6dbb557.png)
![image](https://user-images.githubusercontent.com/24699660/103714263-25197680-4fb6-11eb-9ac6-efcd922c5e3a.png)

**Comment by asemev** [comment]
Cool thank you. Yours look very nice. I tried the same but it says 'icon required'. Did you download the icon from somewhere?

**Comment by asemev** [comment]
Cool thank you. I did the same now and it works.
