### ISSUE TITLE
Forward compatibility home assistant 2021.3

### ISSUE THREAD

**Issue by titiviking** [arjenvrh/audi_connect_ha#65]
Custom component should include a manifest as described in the latest release from HA.

Currently a warning is displayed in logs as intermediate heads up. Future HA updates would block custom integration that don't comply.

2021-03-08 10:26:44 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'audiconnect'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'audiconnect'

**Comment by TheDK** [comment]
Yes, would be great if this could be added, it's a great integration!

**Comment by TheDK** [comment]
@arjenvrh Just want to let you know that the deadline for the version key in the manifest file is end of May - HA version 2021.6 will then block the custom component from loading.

**Comment by arjenvrh** [comment]
Added the version key to the manifest file

**Comment by TheDK** [comment]
Thanks very much - the error message is gone after update. Highly appreciated!
