### ISSUE TITLE
Receiving bad gateway/bad request when calling API

### ISSUE THREAD

**Issue by nickelnine** [arjenvrh/audi_connect_ha#66]
I added the integration successfully using CA region (Canada) with SPIN but when calling lock/unlock I am getting:

`Unable to lock WBANXXXXXX1234567: 502, message='Bad Gateway', url=URL('https://msg.volkswagen.de/fs-car/bs/rlu/v1/Audi/CA/vehicles/WBANXXXXXX1234567/actions')`

Tried also adding the integration with Canada region and getting a similar response when calling lock/unlock:

`Unable to lock WBANXXXXXX1234567: 400, message='Bad Request', url=URL('https://msg.volkswagen.de/fs-car/bs/rlu/v1/Audi/Canada/vehicles/WBANXXXXXX1234567/actions')`

VIN hidden.

**Comment by arjenvrh** [comment]
Can you check if this problem persists after the last update (#50)

**Comment by nickelnine** [comment]
Hi @arjenvrh , I uninstalled and reinstalled but still facing the same error:

```
Logger: custom_components.audiconnect.util
Source: custom_components/audiconnect/util.py:25
Integration: Audi Connect (documentation)
First occurred: 8:36:17 PM (2 occurrences)
Last logged: 8:36:41 PM

Unable to unlock <VIN>: 502, message='Bad Gateway', url=URL('https://msg.volkswagen.de/fs-car/bs/rlu/v1/Audi/CA/vehicles/<VIN>/actions')
Unable to lock <VIN>: 502, message='Bad Gateway', url=URL('https://msg.volkswagen.de/fs-car/bs/rlu/v1/Audi/CA/vehicles/<VIN>/actions')
```

**Comment by nickelnine** [comment]
Hi @arjenvrh , latest update still produces the same error message for me. Maybe because my region is CA (Canada)? I've tried with US region and blank region but it states 'invalid credentials'. CA region is the only one that loads (because I am in Canada):

This error originated from a custom integration.

```
Logger: custom_components.audiconnect.util
Source: custom_components/audiconnect/util.py:25
Integration: Audi Connect
First occurred: 7:40:25 AM (1 occurrences)
Last logged: 7:40:25 AM

Unable to lock <VIN>: 502, message='Bad Gateway', url=URL('https://msg.volkswagen.de/fs-car/bs/rlu/v1/Audi/CA/vehicles/<VIN>/actions')
```

**Comment by nickelnine** [comment]
Still not working after the latest [commit](https://github.com/arjenvrh/audi_connect_ha/pull/89):

`502, message='Bad Gateway', url=URL('https://msg.volkswagen.de/fs-car/bs/rlu/v1/Audi/CA/vehicles/`
