### ISSUE TITLE
Stopped working after update to myAudi 4.0

### ISSUE THREAD

**Issue by 8811025080** [arjenvrh/audi_connect_ha#67]
Hi there,

My integration stopped working directly after audi announce new myAudi version 4.0.

Country: Germany

In log i see this:

`2021-03-12 03:00:10 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'audiconnect'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'audiconnect'`

but I remember that the message was there also before and it was working.

**Comment by synack666** [comment]
Same to me.

**Comment by white91wolf** [comment]
same for me:

`2021-03-28 17:26:06 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'audiconnect'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'audiconnect'
`

**Comment by TheDK** [comment]
Still working for me - error message hast nothing do with that, see here:
https://github.com/arjenvrh/audi_connect_ha/issues/65

**Comment by synack666** [comment]
After update today it working fine again!
