### ISSUE TITLE
Invalid Credentials in US after maintenance window

### ISSUE THREAD

**Issue by monsieurlatte** [arjenvrh/audi_connect_ha#77]
Audi did some maint and their app was down for a day or two.  Now I am able to get into the app with the correct username and password but I can't add the integration back in, anyone else?

**Comment by dmulcahey** [comment]
Same here

**Comment by ToranBrown** [comment]
Experiencing the same.

**Comment by zachgilliam** [comment]
Same here

**Comment by heymoe** [comment]
I tried changing the US region to use the v2 auth method in the code as well as made the code changes noted in this other report which the OP said it got things working (https://github.com/arjenvrh/audi_connect_ha/issues/71) but I'm still getting auth failures or what not.

**Comment by gabrielmc9** [comment]
Also experiencing the same issue

**Comment by jriker1** [comment]
Just some more details if helps in the HA logs:

2021-05-05 09:41:09 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2021-05-05 09:41:20 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2021-05-05 09:41:32 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 400, message='', url=URL('https://id.audi.com/v1/token')

Log is being flooded with these messages.

**Comment by jef-pearlman** [comment]
+1 experiencing issue, happy to help debug.  Thanks!

**Comment by shuntfield** [comment]
![image](https://user-images.githubusercontent.com/63152393/118009598-18cb6e80-b346-11eb-975f-714e81a7ae5b.png)
Yup its not working again in the UK either. 

It only failed after a restart of HA for something else I was doing, I have found that also this integration also kind of times out, if you have had your HA instance up for a long time, usually a few days, the token or whatever it is expires and you can no longer connect unless you re-sign in, usually by reloading the integration or restarting home assistant (when this worked)

```
This error originated from a custom integration.


Logger: homeassistant.config_entries
Source: custom_components/audiconnect/audi_api.py:64
Integration: Audi Connect
First occurred: 17:11:03 (2 occurrences)
Last logged: 17:15:04

Error setting up entry audi@<email> for audiconnect
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_api.py", line 45, in request
    async with self._session.request(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_api.py", line 55, in request
    raise ClientResponseError(
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 105, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 194, in get_vehicle_information
    data = await self._api.get(
  File "/config/custom_components/audiconnect/audi_api.py", line 72, in get
    r = await self.request(
  File "/config/custom_components/audiconnect/audi_api.py", line 64, in request
    raise TimeoutError("Timeout error")
asyncio.exceptions.TimeoutError: Timeout error

```

**Comment by shuntfield** [comment]
The strange thing that happens with this is that it logs in and the credentials all work, it just it fails when setting up the entities.

**Comment by shuntfield** [comment]
Mines started working, I am not sure if its a Python thing, because Home Assistant just had an update.

**Comment by jtonk** [comment]
same here.
also noticed that the website https://my.audi.com/ does not show the vehicle data, however the iOS app still does...

**Comment by jtonk** [comment]
it started working again

**Comment by monsieurlatte** [comment]
Still not working for me in the US.

**Comment by monsieurlatte** [comment]
So safe to assume this isn't/can't be fixed?  I know it's working for the ROTW but alas not in the US.

**Comment by knozturk** [comment]
Did US start working again? I am still not being able to login!

**Comment by monsieurlatte** [comment]
Nope, cant get anyone to work on it, and it's not something I can do.

**Comment by Mehick57** [comment]
I am in the US and this integration has not worked for a couple of months. One of the most useful integrations I have installed.  I was hoping the new update was for the us, but still getting the same result when trying to set up the integration. I have reset my password and 4 digit pin several times but still, get "Invalid credentials"! HA reboots don't seem to make a difference.

**Comment by monsieurlatte** [comment]
This all started after the maintenance window, guessing something changed on the audi end for the US but need someone who can code to figure it out.

**Comment by pilot1981** [comment]
anyone solved this?

**Comment by pilot1981** [comment]
you used special char in password?

**Comment by pilot1981** [comment]
I found my problem: special char & in password create the problem of invalid credentials...

My workaround is to change password using a new password without special characters!

**Comment by monsieurlatte** [comment]
> I found my problem: special char & in password create the problem of invalid credentials...
> 
> My workaround is to change password using a new password without special characters!

I was excited but doesnt see to work for me, I tried with just letters and numbers and it didnt work :(

**Comment by heymoe** [comment]
I also tried resetting my password to something without an "&" in it and still no joy here too.

**Comment by tbailey1712** [comment]
Similar situation:
- Started getting failed to connect errors after the Maintenance Window in April
- Reset my password on the new my.audiusa.com and accepted new terms in the app
- Deleted and re-added the integration.  Still cannot connect, Invalid Credentials error

Is an S-PIN still needed?  I used to be able to get it from Equipment Info on my.audi.com, but that site seems to be decommissioned.  The new my.audiusa.com doesn't have maps or the S-PIN.

**Comment by jaygrovr** [comment]
I still cannot login.  I can get in with myaudi app and through the website but the integration is not letting me.  says invalid username?  Do the username and password strings need to have any ' or ", i have tried both to no avail.

**Comment by acortelyou** [comment]
I have found the underlying problem and submitted a PR that should fix login for US.

**Comment by monsieurlatte** [comment]
Omg thank you!!!

On Sep 5, 2021, at 7:49 PM, Alex Cortelyou ***@***.***> wrote:

﻿
I have found the underlying problem and submitted a PR that should fix login for US.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tbailey1712** [comment]
Nice work @acortelyou!  I can confirm that this is working on my HA instance after deleting the integration and reconnecting.  I did need to specify "US" in the region code and left S-PIN blank.
