### ISSUE TITLE
invalid credential

### ISSUE THREAD

**Issue by pilot1981** [arjenvrh/audi_connect_ha#84]
Hi,
after I changed password of my audi account, I'm not able to use integration...

Initially I see all sensor but not updated...

then I removed integration from HACS and installed again...

But when I try to setup it again I obtain invalid credenzial...

no helpful logs...

**Comment by dermotduffy** [comment]
Seems like a duplicate of https://github.com/arjenvrh/audi_connect_ha/issues/77 .

**Comment by pilot1981** [comment]
I found my problem: special char & in password create the problem of invalid credentials...

My workaround is to change password using a new password without special characters!

**Comment by DenisBY** [comment]
I think this issue should be re-opened and fixed via escaping a password.
