### ISSUE TITLE
Integration Stopped working - unable to log in 

### ISSUE THREAD

**Issue by shuntfield** [arjenvrh/audi_connect_ha#88]
This morning (UK) the integration stopped working. No updated data.

I then logged out, restarted, and then tried to log back in. Each attempt immediately returns "Invalid Credentials".

I logged out of my Audi on my phone, and then logged back in, just to make sure my credentials were ok, and also that the app was working, which both were fine.

Seems like something has broken again, or been updated at Audi's end, which has broken the integration.

![image](https://user-images.githubusercontent.com/63152393/138315651-99695346-8214-49cf-892b-f903e31283c5.png)

**Comment by shuntfield** [comment]
Problems back...
It doesn't immediately reject the creds, it waits a little while this time.

**Comment by shuntfield** [comment]
- Doesn't work on Audi App either - they must be having a problem.

**Comment by pilot1981** [comment]
@Mr-Staffman can alkso you look at #94 ?
