### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by tnagels** [arjenvrh/audi_connect_ha#9]
With the new upgrade I get a lot of errors in my log. It also seems to lock up Hassio when the occur (I edited out some potentially sensitive data):

`Error saving event: <Event audiconnect_refresh_vehicle_data_completed[L]: vin=EDITED>
18:36 components/recorder/__init__.py (ERROR)`

`Error executing query: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_type' at row 1") [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)] [parameters: ('audiconnect_refresh_vehicle_data_completed', '{"vin": "EDITED"}', 'LOCAL', datetime.datetime(2019, 8, 13, 16, 36, 7, 656247, tzinfo=<UTC>), datetime.datetime(2019, 8, 13, 16, 36, 7, 738772), 'EDITED', None)] (Background on this error at: http://sqlalche.me/e/9h9h)
18:36 components/recorder/util.py (ERROR)`

`Unhandled exception
18:36 /usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py (ERROR) - message first occured at 18:36 and shows up 3 times`

`websocket connection is closing.
18:36 components/websocket_api/http.py (WARNING)`

`Ignoring data because we're disconnected!
18:36 __main__.py (WARNING)`

`Got empty response. We think it's disconnect.
18:36 __main__.py (WARNING) - message first occured at 18:31 and shows up 2 times`

`Got exception: 0 bytes read on a total of None expected bytes. Most likely the other side has disconnected!
18:36 __main__.py (WARNING) - message first occured at 18:31 and shows up 2 times`

`API error: {'errorCode': 'gw.error.timeout', 'description': 'Backend Connection Timeout'}
18:36 custom_components/audiconnect/audi_connect_account.py (ERROR) - message first occured at 18:31 and shows up 2 times`

**Comment by arjenvrh** [comment]
Are you periodically calling the audiconnect.refresh_vehicle_data service? Can you temporarily disable this service and see what happens? What version of hassio are you using?

**Comment by tnagels** [comment]
Yes, it seems that the issue occurs when an update is requested. This completely blocks home assistant, both ui and back-end. The interface does not load and I have a sort of heartbeat on my KNX bus which also does not come through during the update.

**Comment by arjenvrh** [comment]
Can you try if the latest version corrects the problem?

**Comment by tnagels** [comment]
I've been out / busy the last couple of days so could not test it, will do so over the weekend!
