### ISSUE TITLE
Entities no loading and ERROR in logs

### ISSUE THREAD

**Issue by oskretc** [arjenvrh/audi_connect_ha#91]
I'm able to add the component but no entity is shown at all, 

when reloading it shows a few errors like::

[homeassistant.config_entries] Error unloading entry [edited username] for switch

[homeassistant.config_entries] Error unloading entry [edited username] for device_tracker

[homeassistant.config_entries] Error unloading entry [edited username] for binary_sensor

[homeassistant.config_entries] Error unloading entry [edited username] for sensor

Any ideas?

**Comment by oskretc** [comment]
This is the error shown, Any Ideas?
![image](https://user-images.githubusercontent.com/4963991/140741103-dc5c567a-8c54-4bde-8259-959f9ce78a6b.png)

**Comment by kailuaphil** [comment]
Same here. also shows this login error:
Login to Audi service failed
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:74
Tried Credentials with and without S-PIN. Both not working. Any ideas? Thank you
