### ISSUE TITLE
no login to Audi since update of os to 7.0

### ISSUE THREAD

**Issue by synack666** [arjenvrh/audi_connect_ha#99]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:89
Integration: Audi Connect
First occurred: 07:27:12 (1 occurrences)
Last logged: 07:27:12

Login to Audi service failed: Extra data: line 1 column 5 (char 4)

**Comment by Puppetmaster91** [comment]
Yeah i have the same, seems like something has changed that bricks the integration :/

**Comment by synack666** [comment]
App for DE without any problems, maintenance info also on DE website

**Comment by unexxx** [comment]
Same issue.

**Comment by bigramonk** [comment]
For me too, the integration stopped working after upgrading to the latest HA Core and OS but I have a few more error messages in my log:
[audi_connect_log.txt](https://github.com/arjenvrh/audi_connect_ha/files/7706658/audi_connect_log.txt)
(to make sure I deleted and re-installed completely the latest version)
thanks

**Comment by angrycatmeowmeow** [comment]
Logs after 7.0, deleted and re-added integration. I was able to set up the integration but setup fails.
[audiconnect.txt](https://github.com/arjenvrh/audi_connect_ha/files/7707794/audiconnect.txt)
.

**Comment by henrikeri** [comment]
Same problem

**Comment by chemgeek** [comment]
Same problem, in US

**Comment by angrycatmeowmeow** [comment]
Mine randomly started working again yesterday. I didn't make any changes.

**Comment by synack666** [comment]
Just restarted, is working, ok, i close this issue, problem on audi site...
